<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.defrimhsn</groupId>
        <artifactId>albanoi-parent</artifactId>
        <version>0.0.3-SNAPSHOT</version>
    </parent>
    <artifactId>albanoi-spring-boot-starter</artifactId>
    <name>Albanoi Spring Boot Starter</name>
    <description>Spring Boot auto-configuration for the Albanoi CQRS gateway</description>
    <dependencies>
        <dependency>
            <groupId>com.defrimhsn</groupId>
            <artifactId>albanoi-commands</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.defrimhsn</groupId>
            <artifactId>albanoi-queries</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
