version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: monthly
    groups:
      maven:
        patterns: ['*']
  - package-ecosystem: npm
    directory: /albanoi-documentation
    schedule:
      interval: monthly
    groups:
      documentation:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
