name: Build and Deploy Docs

on:
  push:
    paths:
      - albanoi-documentation/*
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Change directory
        run: cd albanoi-documentation

      - name: Install dependencies
        run: npm ci

      - name: Build documentation
        run: npm run build

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: defrimhsn
          directory: build
