name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build Albanoi Commands
      run: mvn clean install --file "albanoi-commands/pom.xml"
    - name: Build Albanoi Queries
      run: mvn clean install --file "albanoi-queries/pom.xml"
    - name: Build Albanoi Spring Boot Starter
      run: mvn clean install --file "albanoi-spring-boot-starter/pom.xml"
    - name: Build Spring Boot Sample
      run: mvn clean install --file "samples/spring-boot-sample/pom.xml"
